### ISSUE TITLE
单机多卡跑resnet示例报dataloader错误

### ISSUE THREAD

**Issue by ChenMinQi** [MegEngine/Models#6]
## 环境
1.ubuntu ：
2.0.3：
3.python3.7.3：
4.resnet：

## 复现步骤
1. cd official/vision/classification/resnet
2. python train.py --data=/path/to/imagenet --ngpus=8 --workers=8

## 请提供完整的日志及报错信息
Process Process-2:
Traceback (most recent call last):
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ssd/ssd0/MegEngine_Models/official/vision/classification/resnet/train.py", line 188, in worker
    train_func, train_queue, optimizer, args, epoch=epoch
  File "/ssd/ssd0/MegEngine_Models/official/vision/classification/resnet/train.py", line 219, in train
    for step, (image, label) in enumerate(data_queue):
  File "/home/cmq/anaconda3/lib/python3.7/site-packages/megengine/data/dataloader.py", line 122, in __iter__
    return _ParallelDataLoaderIter(self)
  File "/home/cmq/anaconda3/lib/python3.7/site-packages/megengine/data/dataloader.py", line 216, in __init__
    worker.start()
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/cmq/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects
Exception ignored in: <function _ParallelDataLoaderIter.__del__ at 0x7f42a9f22620>
Traceback (most recent call last):
  File "/home/cmq/anaconda3/lib/python3.7/site-packages/megengine/data/dataloader.py", line 544, in __del__
    if self.__initialized:
AttributeError: '_ParallelDataLoaderIter' object has no attribute '_ParallelDataLoaderIter__initialized'

**Comment by wjfwzzc** [comment]
您好，这是一个已知问题，源于Python3.7的bug（https://bugs.python.org/issue34034）。
我们会在下一版本中规避这个问题。

**Comment by ChenMinQi** [comment]
@wjfwzzc 也就是当前版本只能单卡跑训练是吗。那下个版本是指下一次commit MegEngine的代码？到时候会有相应的whl包吗。

**Comment by wjfwzzc** [comment]
当前版本在python3.6下可以训练。另外分类代码设置`num_workers=0`可以规避错误，但会影响数据的供应速度。
论坛中有相关讨论：<https://discuss.megengine.org.cn/t/topic/180>。
下一版本会有whl包，初步时间点在半个月后（可能会调整）。
