### ISSUE TITLE
无法dump resnet50的量化模型

### ISSUE THREAD

**Issue by qq332982511** [MegEngine/Models#88]
## 环境
1.系统环境：
2.MegEngine版本：
3.python版本：python3.7
4.模型名称：

## 复现步骤
1.
2.
3.

## 请提供关键的代码片段便于追查问题
python3 inference.py -a resnet50 --mode quantized --dump

## 请提供完整的日志及报错信息
Traceback (most recent call last):
  File "inference.py", line 110, in <module>
    main()
  File "inference.py", line 50, in main
    model = models.__dict__[args.arch]()
  File "/home/liujunjie/AIBenchmark/models/model-zoo/megengine_quant/quantization/models/resnet.py", line 296, in resnet50
    m = ResNet(Bottleneck, [3, 4, 6, 3], **kwargs)
  File "/home/liujunjie/AIBenchmark/models/model-zoo/megengine_quant/quantization/models/resnet.py", line 162, in __init__
    self.layer1 = self._make_layer(block, 64, layers[0], norm=norm)
  File "/home/liujunjie/AIBenchmark/models/model-zoo/megengine_quant/quantization/models/resnet.py", line 235, in _make_layer
    norm=norm,
TypeError: __init__() got an unexpected keyword argument 'norm'

**Comment by qq332982511** [comment]
https://github.com/MegEngine/Models/blob/master/official/quantization/models/resnet.py#L95
怀疑是class Bottleneck(M.Module)的init缺norm=M.BatchNorm2d， 参考https://github.com/MegEngine/Models/blob/master/official/quantization/models/resnet.py#L52  class BasicBlock(M.Module)的init虽然接受norm接口，但只起check的作用
